.TH "find_zero.cpp" 3 "Fri Apr 3 2020" "Numerical Methods for Matrices" \" -*- nroff -*-
.ad l
.nh
.SH NAME
find_zero.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'matrix\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ulong \fBfactorial\fP (ulong n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ulong factorial (ulong n)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Numerical Methods for Matrices from the source code\&.
