.TH "matrix.hpp" 3 "Fri Apr 3 2020" "Numerical Methods for Matrices" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMatrix\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVERBOSE\fP   false"
.br
.ti -1c
.RI "#define \fBCONDITIONAL_PRINT\fP   if(\fBVERBOSE\fP) cout"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CONDITIONAL_PRINT   if(\fBVERBOSE\fP) cout"

.SS "#define VERBOSE   false"

.PP
\fBAuthor\fP
.RS 4
Siddhant Parekh 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Numerical Methods for Matrices from the source code\&.
