.TH "matrixTransformations.cpp" 3 "Fri Apr 3 2020" "Numerical Methods for Matrices" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrixTransformations.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'matrix\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBMatrix\fP \fBaugmentMatrices\fP (const \fBMatrix\fP &A, const \fBMatrix\fP &B)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBMatrix\fP augmentMatrices (const \fBMatrix\fP & A, const \fBMatrix\fP & B)"

.PP
\fBParameters\fP
.RS 4
\fIA\fP is a reference to the coefficient matrix 
.br
\fIB\fP is a reference to the constant matrix 
.RE
.PP
\fBReturns\fP
.RS 4
An augmented matrix\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Numerical Methods for Matrices from the source code\&.
